/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Model.Vinho;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class CadastroVinho extends javax.swing.JFrame {

    /**
     * Creates new form CadastroProduto
     */
    
        private Vinho objVinho;
    
    public CadastroVinho() {
        initComponents();
        this.objVinho = new Vinho();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        InserirNome = new javax.swing.JTextField();
        InserirDesc = new javax.swing.JTextField();
        QuantEstoque = new javax.swing.JTextField();
        Preco = new javax.swing.JTextField();
        DataCadastro = new javax.swing.JTextField();
        TipoVinho = new javax.swing.JTextField();
        RegiaoVinho = new javax.swing.JTextField();
        MarcaVinho = new javax.swing.JTextField();
        BotaoConfirma = new javax.swing.JButton();
        BotaoMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(72, 14, 38));
        setPreferredSize(new java.awt.Dimension(1920, 1080));
        setSize(new java.awt.Dimension(1920, 1080));

        jPanel1.setBackground(new java.awt.Color(72, 14, 38));

        InserirNome.setText("Digite o nome do vinho");
        InserirNome.setMargin(new java.awt.Insets(3, 6, 2, 6));
        InserirNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InserirNomeActionPerformed(evt);
            }
        });

        InserirDesc.setText("Descrição do vinho");

        QuantEstoque.setText("Quantidade em estoque");

        Preco.setText("Preço do vinho");

        DataCadastro.setText("Data de cadastro");

        TipoVinho.setText("Tipo de vinho");

        RegiaoVinho.setText("Região de fabricação");

        MarcaVinho.setText("Marca do vinho");

        BotaoConfirma.setText("Cadastrar");

        BotaoMenu.setText("Menu");
        BotaoMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(InserirNome)
                    .addComponent(InserirDesc)
                    .addComponent(QuantEstoque)
                    .addComponent(Preco)
                    .addComponent(DataCadastro)
                    .addComponent(TipoVinho)
                    .addComponent(RegiaoVinho)
                    .addComponent(MarcaVinho, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(132, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BotaoMenu)
                .addGap(112, 112, 112)
                .addComponent(BotaoConfirma)
                .addGap(193, 193, 193))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(InserirNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(InserirDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(QuantEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Preco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(DataCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(TipoVinho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(RegiaoVinho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(MarcaVinho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotaoConfirma)
                    .addComponent(BotaoMenu))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InserirNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InserirNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InserirNomeActionPerformed

    private void BotaoMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoMenuActionPerformed
        //adicionar código pra fechar esse frame e voltar pra tela principal
    }//GEN-LAST:event_BotaoMenuActionPerformed

      private void BotaoConfirmaActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            String nome = InserirNome.getText();
            String descricao = InserirDesc.getText();
            int quantidadeEstoque = Integer.parseInt(QuantEstoque.getText());
            double preco = Double.parseDouble(Preco.getText());
            String dataCadastro = DataCadastro.getText();
            String tipoVinho = TipoVinho.getText();
            String regiaoVinho = RegiaoVinho.getText();
            String marcaVinho = MarcaVinho.getText();

            if (nome.isEmpty() || descricao.isEmpty() || dataCadastro.isEmpty() || tipoVinho.isEmpty() || regiaoVinho.isEmpty() || marcaVinho.isEmpty()) {
                throw new IllegalArgumentException("Todos os campos devem ser preenchidos.");
            }

            if (quantidadeEstoque <= 0 || preco <= 0) {
                throw new IllegalArgumentException("Quantidade em estoque e preço devem ser maiores que zero.");
            }

            if (this.objVinho.insertVinhoBD(nome, descricao, quantidadeEstoque, preco, dataCadastro, tipoVinho, regiaoVinho, marcaVinho)) {
                JOptionPane.showMessageDialog(rootPane, "Vinho Cadastrado com Sucesso!");

                // Limpa os campos da interface
                InserirNome.setText("");
                InserirDesc.setText("");
                QuantEstoque.setText("");
                Preco.setText("");
                DataCadastro.setText("");
                TipoVinho.setText("");
                RegiaoVinho.setText("");
                MarcaVinho.setText("");
            } else {
                JOptionPane.showMessageDialog(rootPane, "Erro ao cadastrar vinho.");
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao converter número.");
        } catch (IllegalArgumentException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroVinho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroVinho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroVinho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroVinho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroVinho().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoConfirma;
    private javax.swing.JButton BotaoMenu;
    private javax.swing.JTextField DataCadastro;
    private javax.swing.JTextField InserirDesc;
    private javax.swing.JTextField InserirNome;
    private javax.swing.JTextField MarcaVinho;
    private javax.swing.JTextField Preco;
    private javax.swing.JTextField QuantEstoque;
    private javax.swing.JTextField RegiaoVinho;
    private javax.swing.JTextField TipoVinho;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
